name: Backend Pegadaian Development

on:
  push:
    branches: [master]

jobs:
  backend-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Deploy to dev instance and change permission dev instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_ADMIN }}
          key: ${{ secrets.PLATFORM_PRODUCTION_RSA_KEY }}
          passphrase: ${{ secrets.PASSPHRASE_ARIFIN }}
          port: ${{ secrets.SSH_PORT_PROD }}
          script: |
            cd /var/www
            sudo chown -R arifin:admin pegadaian
            cd /var/www/pegadaian
            git checkout master
            git fetch
            git pull origin master
            exit

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          script: |
            cd /var/www
            sudo chown -R arifin:admin pegadaian
            cd /var/www/pegadaian

      - name: Install composer dependencies
        run: |
          composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: test
        run: php artisan test

      - name: Change permission folder and file on instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_ADMIN }}
          key: ${{ secrets.PLATFORM_PRODUCTION_RSA_KEY }}
          port: ${{ secrets.SSH_PORT_PROD }}
          script: |
            cd /var/www
            sudo chown -R 1000:33 pegadaian
            cd /var/www/pegadaian
            sudo chmod -R ug+rwx storage bootstrap/cache
            exit
