name: Backend Pegadaian Development

on:
  push:
    branches: [master]

jobs:
  backend-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Deploy to dev instance and change permission dev instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_ADMIN }}
          key: ${{ secrets.PLATFORM_PRODUCTION_RSA_KEY }}
          port: ${{ secrets.SSH_PORT_PROD }}
          script: |
            cd /var/www/v3
            sudo chown -R admin:admin backend
            cd /var/www/pegadaian
            git checkout v3
            git fetch
            git pull origin v3
            exit

      - name: Install Dependencies and clear cach artisan
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_ADMIN }}
          key: ${{ secrets.PLATFORM_PRODUCTION_RSA_KEY }}
          port: ${{ secrets.SSH_PORT_PROD }}
          script: |
            cd /var/www/pegadaian
            composer install
            php artisan optimize:clear
            exit

      - name: Change permission folder and file on instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USERNAME_ADMIN }}
          key: ${{ secrets.PLATFORM_PRODUCTION_RSA_KEY }}
          port: ${{ secrets.SSH_PORT_PROD }}
          script: |
            cd /var/www/v3
            sudo chown -R www-data:www-data backend
            cd /var/www/pegadaian
            sudo chmod -R ug+rwx storage bootstrap/cache
            exit
